### ISSUE TITLE
Create a critique for Team Books' website.

### ISSUE THREAD

**Issue by alitarekrashed** [cedricgc/cs373-idb#70]
http://litdb.me/

Answer these questions:

- What did we do well?
- What did we learn?
- What can we do better?
- What puzzles us?

**Comment by will-truong** [comment]
it's down, when should it be available for critique?

**Comment by alitarekrashed** [comment]
Hm, not sure. We could give it a couple days, but if it's not up soon it might be a good idea to reach out to one of the people on the team and see when their final version would be up.

**Comment by alitarekrashed** [comment]
Done
