### ISSUE TITLE
Get a navbar up on all the pages

### ISSUE THREAD

**Issue by alitarekrashed** [cedricgc/cs373-idb#9]
should be defined in base.html so the rest of the pages can just inherit it.

bootstrap uses href to navigate.

**Comment by cedricgc** [comment]
I defined a layout.html that sets up the title and pull angularjs for you in the frontend, I am unsure how much work to split between Jinja2 and Angular though

**Comment by alitarekrashed** [comment]
yeah, I think we'll have to toy around and figure out what ends up working best.

**Comment by alitarekrashed** [comment]
closing now that we've merged
